"""Tests for DataFrame serialization helpers."""

import tempfile
from pathlib import Path

import pandas as pd
import pytest

from mcp_server.serialization import df_from_json, df_to_json, maybe_cache


def test_df_roundtrip_small_json():
    df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
    payload = df_to_json(df)
    restored = df_from_json(payload)
    pd.testing.assert_frame_equal(df, restored)


def test_maybe_cache_small_returns_json():
    df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
    result = maybe_cache(df, cache_path="/tmp")
    assert result["uri"].startswith('{"')
    assert result["rows"] == 2
    assert "schema" in result


def test_maybe_cache_large_returns_file_uri(tmp_path):
    rows = 60_000
    df = pd.DataFrame({"a": range(rows), "b": range(rows)})
    cache_path = str(tmp_path)
    result = maybe_cache(df, cache_path=cache_path)
    assert result["uri"].startswith("file://")
    assert result["uri"].endswith(".parquet")
    assert result["rows"] == rows


def test_df_from_json_file_uri_reads_parquet(tmp_path):
    df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
    path = tmp_path / "df.parquet"
    df.to_parquet(path)
    restored = df_from_json(f"file://{path}")
    pd.testing.assert_frame_equal(df, restored)


def test_no_cache_path_returns_json():
    df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
    result = maybe_cache(df, cache_path=None)
    assert result["uri"].startswith('{"')


def test_df_from_json_rejects_traversal(tmp_path, monkeypatch):
    """file:// URIs outside allowed roots must be rejected to prevent path traversal."""
    monkeypatch.setenv("MCP_FILE_ROOTS", str(tmp_path))
    outside = Path(tempfile.gettempdir()).parent / "outside.json"
    with pytest.raises(ValueError, match="file:// path outside allowed roots"):
        df_from_json(f"file://{outside}")


def test_df_from_json_generated_file_not_in_roots(tmp_path):
    """Files generated by maybe_cache can be read even outside MCP_FILE_ROOTS."""
    df = pd.DataFrame({"a": range(60_000)})
    result = maybe_cache(df, cache_path=str(tmp_path))
    restored = df_from_json(result["uri"])
    assert len(restored) == 60_000
