"""DataFrame serialization helpers for MCP tool payloads.

All DataFrames cross the tool boundary as either:
- a small JSON string (orient=split), or
- a file:// URI pointing at a parquet/json file on disk.

Pickle is intentionally never used for DataFrame transport.
"""

import hashlib
import io
import json
import os
import tempfile
from pathlib import Path
from typing import Set

import pandas as pd


LARGE = 50_000  #: rows threshold above which we prefer file-backed transport

# Registry of file paths produced by this process via ``maybe_cache``.
# These paths are trusted for subsequent reads in ``df_from_json``.
_GENERATED_FILE_PATHS: Set[Path] = set()


def _allowed_file_roots() -> list[Path]:
    """Return the list of directories from which file:// reads are allowed.

    Defaults to the current working directory and the system temporary
    directory.  Additional roots may be supplied via the ``MCP_FILE_ROOTS``
    environment variable as an OS-specific path list.
    """
    roots = [Path(os.getcwd()).resolve()]
    try:
        roots.append(Path(tempfile.gettempdir()).resolve())
    except Exception:  # pragma: no cover
        pass
    env_roots = os.environ.get("MCP_FILE_ROOTS", "")
    if env_roots:
        for raw in env_roots.split(os.pathsep):
            raw = raw.strip()
            if raw:
                roots.append(Path(raw).resolve())
    # de-duplicate while preserving order
    seen: set[Path] = set()
    result: list[Path] = []
    for root in roots:
        if root not in seen:
            seen.add(root)
            result.append(root)
    return result


def _validate_file_path(path: str) -> Path:
    """Validate and resolve a file:// path, raising ValueError if unsafe.

    The path must be absolute and, unless it was generated by this
    process, must resolve to a location inside one of the allowed roots.
    """
    p = Path(path)
    if not p.is_absolute():
        raise ValueError(f"file:// URI must use an absolute path: {path}")
    resolved = p.resolve()
    # If this server produced the file in the current process, allow it.
    if resolved in _GENERATED_FILE_PATHS:
        return resolved
    allowed = _allowed_file_roots()
    for root in allowed:
        try:
            resolved.relative_to(root)
            return resolved
        except ValueError:
            continue
    raise ValueError(f"file:// path outside allowed roots: {path}")


def df_to_json(df: pd.DataFrame) -> str:
    """Serialize a DataFrame to a JSON string using orient=split."""
    return df.to_json(orient="split")


def df_from_json(payload: str) -> pd.DataFrame:
    """Deserialize a DataFrame from JSON or a file:// URI.

    Supports:
      - file://<path>.parquet
      - file://<path>.json
      - raw JSON string (orient=split)
    """
    if not isinstance(payload, str):
        raise TypeError("DataFrame payload must be a string (JSON or file:// URI)")
    if payload.startswith("file://"):
        path = payload[len("file://"):]
        resolved = _validate_file_path(path)
        if str(resolved).lower().endswith(".parquet"):
            return pd.read_parquet(resolved)
        if str(resolved).lower().endswith(".json"):
            return pd.read_json(resolved, orient="split")
        raise ValueError(f"Unsupported file extension for file:// URI: {path}")
    return pd.read_json(io.StringIO(payload), orient="split")


def _build_schema_hint(df: pd.DataFrame) -> dict:
    """Return a serializable dtype map for client-side hints."""
    return {col: str(dtype) for col, dtype in df.dtypes.items()}


def maybe_cache(df: pd.DataFrame, cache_path: str | None) -> dict:
    """Return a dict describing a DataFrame payload.

    If the DataFrame is large (>LARGE rows) and ``cache_path`` is provided,
    it is written to a parquet file and a file:// URI is returned.
    Otherwise a JSON string is returned.

    Returns
    -------
    dict with keys:
      uri (str): JSON string or file:// URI
      rows (int): number of rows
      schema (dict): dtype map
    """
    if cache_path and len(df) > LARGE:
        os.makedirs(cache_path, exist_ok=True)
        digest = hashlib.sha1(pd.util.hash_pandas_object(df).values).hexdigest()[:12]
        fp = Path(cache_path) / f"{digest}.parquet"
        if not fp.exists():
            df.to_parquet(fp)
        resolved = fp.resolve()
        _GENERATED_FILE_PATHS.add(resolved)
        return {
            "uri": f"file://{resolved}",
            "rows": len(df),
            "schema": _build_schema_hint(df),
        }
    return {
        "uri": df_to_json(df),
        "rows": len(df),
        "schema": _build_schema_hint(df),
    }


def serialize_result(df: pd.DataFrame, cache_path: str | None = None) -> dict:
    """Backward-compatible alias for maybe_cache that returns the payload dict."""
    return maybe_cache(df, cache_path)


def load_payload(payload: str) -> pd.DataFrame:
    """Alias of df_from_json with a clearer name."""
    return df_from_json(payload)
